name 'wordpress'
maintainer 'Oscar Eduardo Saavedra Tarazonat - Yeisson Jimenez Bustos Harry - Mauricio Cuesta Gamboa - Sebastián Noreña Márquez '
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures wordpress'
version '0.1.0'
chef_version '>= 16.0'
cookbook 'mysql', '>= 5.3.6'
